// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe35P6avUdVz06xI_d6P21im9gU_hnJKs',
    appId: '1:490754899998:web:7afcfc1978dcb0c7536e0f',
    messagingSenderId: '490754899998',
    projectId: 'inventory-mobile-system',
    authDomain: 'inventory-mobile-system.firebaseapp.com',
    storageBucket: 'inventory-mobile-system.firebasestorage.app',
    measurementId: 'G-5KM9FNCPXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXZCkW8s2HhzcqfqYoPs1D9V_-RKZoGQ',
    appId: '1:490754899998:android:84005f8f1ace3cee536e0f',
    messagingSenderId: '490754899998',
    projectId: 'inventory-mobile-system',
    storageBucket: 'inventory-mobile-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9xQOZDMcr0puSfhDITAIZjIm3d4aDQEE',
    appId: '1:490754899998:ios:31fbdc4f317e02e0536e0f',
    messagingSenderId: '490754899998',
    projectId: 'inventory-mobile-system',
    storageBucket: 'inventory-mobile-system.firebasestorage.app',
    iosBundleId: 'com.example.laporApp',
  );
}
